name: Build KivyMD App

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools=69.5.1 wheel pyinstaller==5.13.0
        pip install -r requirements

    - name: Build with PyInstaller
      run: pyinstaller GatewayPi.spec

    - name: Archive Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wifi-status-app
        path: dist/
