name: Build KivyMD App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build application for arch ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch:
          - "x86_64"
#          Cross compilation is not working yet :(
#          - "aarch64"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        if: matrix.arch == 'aarch64'
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
        with:
          platforms: arm64

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12" # Specify the Python version you need

      - name: Install ubuntu dependencis
        run: |
          sudo apt update
          sudo apt -y install libmtdev1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools==69.5.1 wheel pyinstaller==5.13.0
          pip install -r requirements.txt


      - name: Build with PyInstaller
        run: xvfb-run pyinstaller --log-level INFO --distpath dist/${{ matrix.arch }} GatewayPi.spec

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GatewayPi-${{ matrix.arch }}
          path: dist/${{ matrix.arch }}
